[package]
name = "wgsl_preproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
naga = { version = "0.14.2", features = ["wgsl-out", "wgsl-in"] }
regex = "1.10.2"
